### ISSUE TITLE
Tooltip du massif précédent ouvert par défaut en arrivant sur un nouveau massif

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#11]
**Description**
Je suis sur la page d'un massif et j'ouvre le tooltip du n-ième POI de ce massif.
Lorsque je change de massif, le tooltip du n-ième POI de ce nouveau massif est ouvert par défaut.

**Screen vidéo**
[bug refuges.mov.zip](https://github.com/benoitdemaegdt/refuges/files/4571618/bug.refuges.mov.zip)

**Comment by benoitdemaegdt** [comment]
fixed https://github.com/benoitdemaegdt/refuges/commit/84599857f1c557a302f31758776e8fef05670a1e
