### ISSUE TITLE
Page détails - Masquer la section lorsqu'il n'y a pas de data dispo pour ce POI

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#12]
Cela concerne particulièrement les sections "Description" et "Accès"

**Comment by benoitdemaegdt** [comment]
related to https://github.com/benoitdemaegdt/refuges/issues/7

**Comment by benoitdemaegdt** [comment]
fixed: https://github.com/benoitdemaegdt/refuges/commit/843f7623ec3c22ae67b6f62a15e8bdebd3ad44a6
