### ISSUE TITLE
Reset search bar content when we leave the searched page

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#19]
Le fait de conserver la dernière recherche dans la search bar peut créer de la confusion (2 screen vidéos en exemple).
Sur la 2ème je me retrouve avec "Belledonne" dans la search bar alors que je suis sur la page de la Chartreuse.

[search_bar.mov.zip](https://github.com/benoitdemaegdt/refuges/files/4629327/search_bar.mov.zip)
[search_bar2.mov.zip](https://github.com/benoitdemaegdt/refuges/files/4629325/search_bar2.mov.zip)

**Comment by benoitdemaegdt** [comment]
fixed : https://github.com/benoitdemaegdt/refuges/commit/c93da5aebd4b28de732e2aae8236f079e5656507
