### ISSUE TITLE
Update search bar content

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#29]
Les 2 nouveaux massifs (Ecrins et Bauges) n'apparaissent pas dans la search bar (cf screen)
<img width="1434" alt="Capture d’écran 2020-05-26 à 10 22 44" src="https://user-images.githubusercontent.com/64357446/82877921-160c1980-9f3b-11ea-839a-35e8d948bff5.png">

Cela soulève une question : doit-on continuer d'intégrer les massifs à la search bar ?
Sachant que : 
- dés qu'on aura intégrer ces 2 nouveaux massifs l'utilisateur ne verra par défaut que des massifs dans la search bar ==> comprendra-t-il qu'il peut rechercher une cabane ?
- les massifs sont accessibles facilement depuis le burger menu

**Comment by benoitdemaegdt** [comment]
https://github.com/benoitdemaegdt/refuges/commit/3d3e58360a7838c368f4b165d0b7ffc214dfdf4d
