### ISSUE TITLE
Homogénéiser le wording "cabane" / "refuge"

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#30]
Homogénéiser le wording "cabane" / "refuge" entre le titre et le filtre des pages Massif.
<img width="1431" alt="Capture d’écran 2020-05-26 à 13 19 34" src="https://user-images.githubusercontent.com/64357446/82898228-2fbc5980-9f59-11ea-889f-130310cf6d3a.png">

A faire également avec les boutons "Voir les cabanes" de la home.

**Comment by benoitdemaegdt** [comment]
tu préfères quel mot ? cabane ou refuge ?

**Comment by gaultierbonlarron** [comment]
Je trouve que "refuge" c'est pas mal parce qu'on sens littéral ça englobe tout endroit dans lequel tu peux te réfugier pour la nuit :
- refuge gardé
- cabane non gardée 
- etc

**Comment by benoitdemaegdt** [comment]
https://github.com/benoitdemaegdt/refuges/commit/83b6bdf247ea92e41cfc953906744f19e30bb4a8
