### ISSUE TITLE
Mobile - Bug "Détails" button on map

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#46]
**Description**
GIVEN I have yet opened a "Détails" page from the map view and used the "Retour" button
WHEN I want to open a new "Détails" page from the map view
THEN I "Détails" button doesn't work

Video
[File from iOS (2).MP4.zip](https://github.com/benoitdemaegdt/refuges/files/4740075/File.from.iOS.2.MP4.zip)

**Comment by benoitdemaegdt** [comment]
fixed : https://github.com/benoitdemaegdt/refuges/commit/ab628e4e62c6b631883e895f5e89ab793be731ce
