### ISSUE TITLE
Scroll up to the top of the page when the user changes page

### ISSUE THREAD

**Issue by gaultierbonlarron** [benoitdemaegdt/refuges#49]
**Today**
GIVEN I'm on the shacks list of a massif
WHEN I change page
THEN I'm _at the bottom_ of the new page

[pages.mov.zip](https://github.com/benoitdemaegdt/refuges/files/4740522/pages.mov.zip)

**What we want**
GIVEN I'm on the shacks list of a massif
WHEN I change page
THEN I'm _at the top_ of the new page

**Comment by benoitdemaegdt** [comment]
https://github.com/benoitdemaegdt/refuges/commit/cc51edb58550f38c16ff0277b0a5651a109920e4
