### ISSUE TITLE
redesigner la vue cabane

### ISSUE THREAD

**Issue by benoitdemaegdt** [benoitdemaegdt/refuges#7]
## Description
- [x] enlever les rubriques "Accès" et "À propos" si on n'a pas de data la dessus
- [ ] dans la rubrique "Équipement", ajouter : "bois à proximité", "matelas", "couvertures"

**Comment by gaultierbonlarron** [comment]
Sortir l'altitude de la section "Equipements"
La déplacer à droite sur la même ligne que le nom de la cabane ?

**Comment by benoitdemaegdt** [comment]
done: https://github.com/benoitdemaegdt/refuges/commit/aec30ebd5601f8e152b7cc2f7258b0dbb1195ac1
